name: on-push
on: [push]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Install Trunk
        uses: jetli/trunk-action@v0.4.0
      - name: Run tests
        run: cargo test --features integration-test
      - name: Build
        run: trunk --config ./Trunk.itch_io.toml build --release --features wasm-logging
      - name: Install butler
        if: github.ref == 'refs/heads/main'
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: Release on itch.io
        if: github.ref == 'refs/heads/main'
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: ./butler push dist remieven/greatancientsimulator:web --if-changed
