name: on-push
on:
  - push
  - workflow_dispatch

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Check code
        run: npm run check
      - name: Run tests
        run: npm run test
      - name: Build
        run: npm run build
      - name: Install butler
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: Release on itch.io
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: ./butler push dist remieven/${{ github.ref == 'refs/heads/main' && 'outplant' || 'outplant-dev' }}:web --if-changed
